apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc-{{ include "operator-intro-env.fullname" . }}
  labels:
    {{- include "operator-intro-env.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "operator-intro-env.selectorLabels" . | nindent 4 }}
